### PR TITLE
Add Tor linux arm64

### PR DESCRIPTION
**Pull request by linhkikuchi**
For https://github.com/brave/devops/issues/8519
Resolves https://github.com/brave/brave-core-crx-packager/issues/569

### CODE REVIEW

**Comment by fmarier** [comment]
@boocmp I believe you wanted to combine the two Linux components into a single multi-architecture one, right?

**Comment by linhkikuchi** [comment]
> @boocmp I believe you wanted to combine the two Linux components into a single multi-architecture one, right?

I thought we want to separate them? https://github.com/brave/brave-core-crx-packager/pull/571#issuecomment-1432461516
https://github.com/brave/devops/pull/9136/files#diff-641aa9ced0739e4e477437751f1c5e0073b38d0da4526a50dacaa806c363cec0R73

@boocmp for tor-pluggable-transports, I see that we combine x86 and x64 for snowflake & obfs4 binaries, so the components are also combined. I believe they support arm64 now, can we build tor-pluggable-transports for arm64?

**Comment by boocmp** [comment]
We did not combine the x86 and x64 plug-in transports, there are only versions of the PT binaries for x86.
At the moment we've got different CRXes with the different signing keys for every binary. The signing key (public part) defines the crx's Id. So to add new binary we need to create signing key, make new crx, change server's code (written in GO) to support new crx and then add new crx's ID in the browser's code. Google have only one signing key for one component, so it means that different binaries signed with this key will have same ID. When browser is requesting for component it sends ID, version, OS, Arch (and so on) parameters to the server. Server returns the relevant version of CRX. So Google only need to make new crx and change server's code to support new Arch by adding smth like ```if (request_params["arch"] == "arm64") -> return CRX with arm64 version of binary```. 

Examples:
Chromium component registration
https://github.com/chromium/chromium/blob/7926600792276a90c1be81e43c5c05941bb2a432/chrome/browser/component_updater/intervention_policy_database_component_installer.cc#L24

Brave component registration (with different compile time ifs)
https://github.com/brave/brave-core/blob/62e0cc7761474a4339b4969defaf5aa491f871c1/components/tor/brave_tor_pluggable_transport_updater.cc#L22

Brave updater server with hardcoded IDs
https://github.com/brave/brave-core/blob/62e0cc7761474a4339b4969defaf5aa491f871c1/components/ipfs/brave_ipfs_client_updater.h#L28

It's not absolutely necessary to simplify our approach right now, but why not?

@linhkikuchi
I have not tried to build PTS for arm64, but I suppose that passing 'arm64' in the 'GOARCH' parameter of the build script should work.

**Review by mihaiplesa — APPROVED** [review]

**Comment by prusnak** [comment]
When will the CRX file appear at https://tor.bravesoftware.com/release/monolafkoghdlanndjfeebmdfkbklejg ?

**Pull request merged**
