### PR TITLE
Fix lint errors and run it as part of CI

### LINKED ISSUE #267: lint failures
#264 updates standard to the latest version, which causes some lint failures (though they might already exist). once these are fixed, lint should be added to the CI command.

### PR DESCRIPTION
**Pull request by fmarier**
Resolves #267 

I highly recommend looking at each commit separately. One of those (the largest one) is the output of running a tool to fix a lot of straightforward lint errors. The other ones are manual edits and should be looked at more carefully.

### CODE REVIEW

**Comment by diracdeltas** [comment]
the codeql failure doesn't seem like a big deal, should be fine to ignore (but i wonder what this code is supposed to be doing): https://github.com/brave/brave-core-crx-packager/security/code-scanning/10

**Comment by fmarier** [comment]
I've added the CodeQL fixes to this PR since they were pretty simple to fix too.

> i wonder what this code is supposed to be doing

Elsewhere in that file, it's replacing '.' with '_', so I'm guessing it's a copy/paste "error".

**Review by atuchin-m — APPROVED** [review]

**Comment by iambrianfung** [comment]
lgtm for the Brave Ads Resources

**Review by petemill — APPROVED** [review]
JS looks good! Nice work fixing all this

**Comment by fmarier** [comment]
I kicked off builds for all of the Jenkins dev jobs that use this repo:

- https://ci.brave.com/job/brave-core-ext-local-data-files-update-publish-dev/635/
- https://ci.brave.com/job/brave-core-ext-import-cws-components-dev/10/
- https://ci.brave.com/job/brave-core-ext-ntp-sponsored-publish-dev/250
- https://ci.brave.com/job/brave-core-ext-ipfs-component-publish-dev/217
- https://ci.brave.com/job/brave-core-ext-ad-block-update-publish-dev/123/
- https://ci.brave.com/job/brave-core-ext-tor-client-update-publish-dev/64/
- https://ci.brave.com/job/brave-core-ext-ntp-super-referrer-publish-dev/35
- https://ci.brave.com/job/brave-core-ext-user-model-installer-publish-dev/270
- https://ci.brave.com/job/brave-core-ext-youtubedown-component-upload-dev/22
- https://ci.brave.com/job/brave-core-ext-ntp-background-images-component-dev/11
- https://ci.brave.com/job/brave-core-ext-https-everywhere-update-publish-dev/163
- https://ci.brave.com/job/brave-core-ext-ethereum-remote-client-update-publish-dev/53
- https://ci.brave.com/job/brave-core-ext-speedreader-data-files-update-publish-dev/25
- https://ci.brave.com/job/brave-core-ext-wallet-data-files-update-publish-dev/76
- https://ci.brave.com/job/brave-core-ext-tor-pluggable-transports-publish-dev/36

and they all passed, with the exception of the last one, though that's for a feature which hasn't shipped yet and the error didn't seem related to my changes.

In addition to checking that the builds passed, I also looked at the build output for any new errors and didn't see any.

**Pull request merged**
