### PR TITLE
Replace `request` with `fetch`

### PR DESCRIPTION
**Pull request by antonok-edm**
The `request` package is deprecated and unmaintained. The same functionality can be achieved with the built-in `fetch` API, so I removed the dependency and updated the code accordingly.

Progress towards https://github.com/brave/brave-core-crx-packager/issues/380.

### CODE REVIEW

**Comment by antonok-edm** [comment]
This should also fix the issue with the Estonian regional adblock list I noted in https://github.com/brave/brave-core-crx-packager/issues/380#issuecomment-1340320833

**Review by diracdeltas — APPROVED** [review]
change lgtm but CI is failing with a node gyp error: https://github.com/brave/brave-core-crx-packager/actions/runs/3643168897/jobs/6151103409

**Comment by antonok-edm** [comment]
Also of note: we'd need to run this in Node 18 (`Readable.fromWeb` is only available starting in Node 17).

**Comment by antonok-edm** [comment]
@diracdeltas looks like a Python 2->3 error.

> ```
> npm ERR! npm ERR! gyp ERR! stack Error: Python executable "/usr/bin/python" is v3.10.6, which is not supported by gyp.
> npm ERR! npm ERR! gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
> ```

I'm not sure what's causing that specifically, but I assume Node 18 has a better chance of handling Python 3 correctly, too.

**Comment by antonok-edm** [comment]
I see that `fetch` is also just not supported at all in Node 16 either, so even more reason to upgrade to 18.

**Review by mihaiplesa — APPROVED** [review]

**Comment by mihaiplesa** [comment]
This is good to go now.

**Pull request merged**
