### PR TITLE
Add extension whitelist to local-data-files

### PR DESCRIPTION
**Pull request by pilgrim-brave**

### CODE REVIEW

**Comment by bbondy** [comment]
cc @mihaiplesa we'd need to add this like the other extensions to jenkins please.  Run on demand only is good.

**Comment by mihaiplesa** [comment]
on it soon, tracking via https://github.com/brave/devops/issues/734

**Comment by mihaiplesa** [comment]
from what I'm seeing it already does `"data-files-local-data-files": "npm run data-files-tracking-protection && npm run data-files-autoplay-whitelist && npm run data-files-extension-whitelist"` which we're calling so think we're good already

**Comment by bbondy** [comment]
oops got it, thanks.

**Pull request merged**
