### PR TITLE
Update aws-sdk to latest version

### PR DESCRIPTION
**Pull request by spylogsster**
Resolves https://github.com/brave/brave-browser/issues/20196

- Fixing audit issue by updating library to latest version

### CODE REVIEW

**Review by mihaiplesa — APPROVED** [review]

**Review by mihaiplesa — CHANGES_REQUESTED** [review]
CI failed as `package-lock.json` needs update as well.

**Comment by spylogsster** [comment]
> CI failed as `package-lock.json` needs update as well.

done

**Review by mihaiplesa — APPROVED** [review]

**Comment by spylogsster** [comment]
seems need also to remove usage of `s3-node-client` as it is deprecated

**Review by mihaiplesa — APPROVED** [review]

**Comment by spylogsster** [comment]
test run looks good https://ci.brave.com/view/all-extensions/job/brave-core-ext-ipfs-component-publish-dev/154/

**Pull request merged**
