### PR TITLE
Select which adblock data files to generate using cli args

### PR DESCRIPTION
**Pull request by tontinton**

### CODE REVIEW

**Review by antonok-edm — COMMENTED** [review]
@tontinton thanks for submitting this!

Unfortunately there are a few dependencies between components that are left in for historical reasons, e.g. the regional data files depend on the default component files [here](https://github.com/brave/brave-core-crx-packager/blob/8164754e26e6305dd6504902bde50d9c3c9cf70f/scripts/generateAdBlockRustDataFiles.js#L114).

I'm hoping to get rid of those dependencies eventually, but I don't want to suddenly break things for older browser versions that haven't updated in a while. In the meantime we still have to do most<sup>†</sup> of these in order.

So, I can't merge this just yet, but hopefully I can get to it in the future.

<sup>
† I say "most" because the test data files can definitely be generated in parallel... but those can probably be removed altogether, too. I don't believe we have any code that would be using them anymore (<a href="https://github.com/brave/brave-core-crx-packager/pull/701">#701</a>).
</sup>

**Comment by tontinton** [comment]
Ok I updated the PR to only include the cli stuff, will be useful for me (I want to generate only the default list)

**Comment by tontinton** [comment]
bumping, still keeping a fork :(

regional lists sometimes return 404, while the default seem to work all the time.

**Comment by tontinton** [comment]
another final bump? 😅

**Comment by antonok-edm** [comment]
@tontinton sorry for the delay, but the reorganization in #844 should make this significantly easier. All the components will be "self-contained", i.e. not dependent on other component jobs running.

Going forward:
- once merged you could immediately patch [`getAdblockComponentDescriptors`](https://github.com/brave/brave-core-crx-packager/blob/263322d4eba1b87db867d514b5cfa02bff0e1b16/scripts/packageAdBlock.js#L172-L179) to skip the components you're not interested in
- later, I'm planning to move the per-component classes to exports in their own files; making the packaging scripts themselves basically just [these lines](https://github.com/brave/brave-core-crx-packager/blob/263322d4eba1b87db867d514b5cfa02bff0e1b16/scripts/packageAdBlock.js#L172C7-L184). Then you can treat this repo as a library dependency and define a custom entrypoint to drive the logic of which components to package.

**Pull request closed without merging**
